defaults: &defaults
  docker:
    - image: circleci/node:8

version: 2
jobs:
  test:
    <<: *defaults
    steps:
      - checkout
      - run: npm ci
      - run: npm run test-all
      - store_artifacts:
          path: .artifacts

  update_daily:
    <<: *defaults
    steps:
      - checkout
      - run: npm ci
      - run: TRENDING_NOT_DRY_RUN=true TRENDING_LABEL=trending-daily node scripts/update-issues
      - store_artifacts:
          path: .artifacts

  update_weekly:
    <<: *defaults
    steps:
      - checkout
      - run: npm ci
      - run: TRENDING_NOT_DRY_RUN=true TRENDING_LABEL=trending-weekly node scripts/update-issues
      - store_artifacts:
          path: .artifacts

  clean_daily:
    <<: *defaults
    steps:
      - checkout
      - run: npm ci
      - run: TRENDING_NOT_DRY_RUN=true TRENDING_LABEL=trending-daily node scripts/clean-issues
      - run: TRENDING_NOT_DRY_RUN=true TRENDING_LABEL=trending-weekly node scripts/clean-issues

workflows:
  version: 2
  commit_workflow:
    jobs:
      - test

  update_daily_workflow:
    triggers:
      - schedule:
         cron: "0 0 * * *"
         filters:
           branches:
             only:
               - master

    jobs:
      - update_daily

  update_weekly_workflow:
    triggers:
      - schedule:
         cron: "0 3 * * 5"
         filters:
           branches:
             only:
               - master

    jobs:
      - update_weekly

  clean_daily_workflow:
    triggers:
      - schedule:
         cron: "0 22 * * *"
         filters:
           branches:
             only:
               - master

    jobs:
      - clean_daily
